apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "radio.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "radio.name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "radio.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: gmackie/k6gam:v2
        imagePullPolicy: Always
        name: {{ .Chart.Name }}
        ports:
          - containerPort: {{ .Values.service.internalPort }}
